name: Run Tests

on:
  push:
    branches:
      - main

    tags:
      - v*

  pull_request:

  workflow_dispatch:

jobs:
  test-projects:
    strategy:
      matrix:
        project: ["otelslog", "otelzap", "otelzerolog"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang with cache
        id: golang-with-cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: ${{ matrix.project }}/go.mod

      - name: Set up gotestfmt
        run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@v2.5.0

      - name: Run tests
        run: |
          set -euo pipefail
          go test -json -v ./... 2>&1 | gotestfmt -hide empty-packages
